### ISSUE TITLE
Vignette not clear

### ISSUE THREAD

**Issue by dktanwar** [Danis102/seqpac#35]
Hi,

https://github.com/Danis102/seqpac/blob/master/vignettes/seqpac_-_A_guide_to_sRNA_analysis_using_sequence-based_counts.md#44-the-reannotation-workflow

The vignette before "The reannotation workflow" is clear, whereas not after that. For example, the alignment part is missing.

**Comment by Danis102** [comment]
Strange, with our reannotation workflow you can do alignments to any type of fasta reference. This is the important, innovative, difference with the seqpac workflow. Aligments are done late in the analyzes, annotating counted sequences. Thus, seqpac uses sequence-based counts and will preserve the fastq  sequence as far as possible. With feature-based counts, that is more common, you align to a genome and count overlaps with features (e.g a small RNA or exon) in that genome. Here you need to make chooses when counting overlaps, like how many sequence mismatches do you allow and what to do with sequences that multimap or don't map to your genome or overlap with a feature? In seqpac you really don't need to make those choice, or at least you can do it very late in the analysis, where it is easy to see the effects of changing those choices. Since the integrity of the original sequence is preserved it will also make investigating candidate sequences further easy, by for example blasting an interesting sequence at a genome browser etc. That is usually not an option  I have recently updated the master with new streamlined additions to the vignette and manuals. Hope this will help you in the analysis. I will close this issue.
